### ISSUE TITLE
Please add a requirements.txt file

### ISSUE THREAD

**Issue by jorisschellekens** [HumanBojack/BrandSeeker#1]
I would like to request that you start using a requirements file in your Python project.

A requirements file is a simple text file that lists all the dependencies that your project needs in order to run. It makes it easy for other contributors and users to install all the necessary dependencies with a single command.

Not only does using a requirements file make it easier for people to get started with your project, but it also ensures that everyone is using the same version of each dependency. This can help avoid compatibility issues and make it easier to maintain the project in the long run.

Creating a requirements file is easy. You can use the pip freeze command to generate a list of all the dependencies currently installed in your project's virtual environment. This command will output a list of packages with their version numbers, which you can then copy into a file named requirements.txt in the root directory of your project. For example:

```commandline
pip freeze > requirements.txt
```

Once you have created your requirements file, you can use it to install all the necessary dependencies with a single command:

```commandline
pip install -r requirements.txt
```

Thank you for considering this request. Using a requirements file will make it easier for contributors and users to get started with your project, and ensure that everyone is using the same versions of the dependencies.

**Comment by HumanBojack** [comment]
Hello,
A `requirements.txt` file is available under the `App/` folder. It should be enough to run the application.

However, if you want to run the development notebooks, I'm not sure that the dependencies in this file will be enough. I will look into that.
